library globals;

import 'package:flutter/cupertino.dart';

String homeTitle = "Anubhav Adhyayan";
Color primaryColor = Color(0xff00061a);
double webWidthSize = 600;

String privacyPolicyHeader = "#ANUBHAV ADHYAYAN Privacy Policy";
String privacyPolicyFirst =
    "ANUBHAV ADHYAYAN is a portfolio app which is meant to be used by people who are interested in developing something in Flutter.\nWe do not collect any PII (Personally Identifiable Information).";
String privacyPolicyHeaderSecond = "1. SCOPE OF THE PRIVACY POLICY";
String privacyPolicySecond =
    "This Privacy Policy describes the information that ANUBHAV ADHYAYAN Website/App, as part of its normal operations, collects from you, stores, uses and protects. The purpose of this Privacy Policy is to outline and help you understand the various guidelines and procedures that are consistently followed by the ANUBHAV ADHYAYAN Website / App when collecting, storing, utilizing, disclosing or otherwise dealing with any Personal Information. By using the Website / App, you agree to be legally bound by this Privacy Policy, which shall take effect immediately on your first use of the Website / App." +
        "\n\nFurther, the Website may contain hyperlinks to websites operated by parties other than the ANUBHAV ADHYAYAN Website / App which are developed by people over whom the ANUBHAV ADHYAYAN Website / App exercises no control as well as the Website may contain social media plugins. This Privacy Policy does not apply to the practices of such third-party websites or social media websites. Such other third-party/social media websites may place their own cookies on your computer/electronic device, collect data or solicit Personal Information. The ANUBHAV ADHYAYAN Website / App is accordingly not responsible for the privacy practices or the content of such websites." +
        "\n\nAny summary of this Privacy Policy generated by third party software or otherwise shall have no legal effect, shall not be binding on the ANUBHAV ADHYAYAN Website / App, shall not be relied upon in substitute for this Privacy Policy, and neither supersede nor modify this Privacy Policy.";

String privacyPolicyHeaderThird =
    "2. INFORMATION COLLECTED BY THE ANUBHAV ADHYAYAN WEBSITE / APP";
String privacyPolicyThird =
    "The ANUBHAV ADHYAYAN Website / App does not collect any information." +
        "\n\nThe ANUBHAV ADHYAYAN Website may use cookies in the future." +
        "\n\nThe ANUBHAV ADHYAYAN Website / App APIs also automatically receive and record information on ANUBHAV ADHYAYAN Website / App’s web server logs from the user's device including the Internet Protocol (IP) address. IP addresses are recorded for anonymous statistical purposes, administration of this Website and associated servers, and to improve the Website / App's services.";

String privacyPolicyFourthHeader = "3. RESTRICTIVE COVENANTS:";
String privacyPolicyFourth =
    "As mandated by Regulation 3(2) of the Information Technology (Intermediaries Guidelines) Rules, The ANUBHAV ADHYAYAN Website / App hereby cautions and informs that you are not permitted to use the Website to host, display, upload, modify, publish, transmit, update or share any information that:";

String privacyPolicyFourthBullets_a =
    "As mandated by Regulation 3(2) of the Information Technology (Intermediaries Guidelines) Rules, The ANUBHAV ADHYAYAN Website / App hereby cautions and informs that you are not permitted to use the Website to host, display, upload, modify, publish, transmit, update or share any information that:";
String privacyPolicyFourthBullets_b =
    "belongs to another person and to which you do not have any right;";
String privacyPolicyFourthBullets_c =
    "is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;";
String privacyPolicyFourthBullets_d = "harm’s minors in any way;";

String privacyPolicyFourthBullets_e =
    "infringes any patent, trademark, copyright or other proprietary rights;";
String privacyPolicyFourthBullets_f =
    "violates any law for the time being in force;";
String privacyPolicyFourthBullets_g =
    "deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;";
String privacyPolicyFourthBullets_h = "impersonates another person;";
String privacyPolicyFourthBullets_i =
    "contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource;";
String privacyPolicyFourthBullets_j =
    "threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation;";
String privacyPolicyFourthBullets_k =
    "threatens public health or safety; promotion of cigarettes or any other tobacco products or consumption of intoxicant including alcohol and Electronic Nicotine Delivery System (ENDS) & like products that enable nicotine delivery except for the purpose & in the manner and to the extent, as may be approved under the Drugs and Cosmetics Act, 1940 and Rules made thereunder; and";
String privacyPolicyFourthBullets_l =
    "threatens critical information infrastructure.";

String privacyPolicyHeaderFive =
    "In addition, the ANUBHAV ADHYAYAN Website / App further cautions you to prohibit from:";

String privacyPolicyFifthBullets_a =
    "violating or attempting to violate the integrity or security of the Website or any content on the Website;";
String privacyPolicyFifthBullets_b =
    "transmitting any information (including job posts, messages and hyperlinks) on or through the Website that is disruptive or competitive to the provision of services by the ANUBHAV ADHYAYAN Website / App;";
String privacyPolicyFifthBullets_c =
    "intentionally submitting on the Website any incomplete, false or inaccurate information;";
String privacyPolicyFifthBullets_d =
    "making any unsolicited communications to other users of the Website;";
String privacyPolicyFifthBullets_e =
    "using any engine, software, tool, agent or other device or mechanism (such as spiders, robots, avatars or intelligent agents) to navigate or search the Website;";
String privacyPolicyFifthBullets_f =
    "attempting to decipher, decompile, disassemble or reverse engineer any part of the Website;";
String privacyPolicyFifthBullets_g =
    "copying or duplicating in any manner any of the ANUBHAV ADHYAYAN Website / App’s content or other information available on the Website;";
String privacyPolicyFifthBullets_h =
    "framing or hotlinking or deep-linking any content on the Website; and";
String privacyPolicyFifthBullets_i =
    "posting materials to any of the ANUBHAV ADHYAYAN Website / App’s social media pages or otherwise on social media, that are unlawful, fraudulent, libellous, slanderous, defamatory, abusive, harassing, threatening, obscene or infringing on the rights of any third-party, including intellectual property, privacy/confidentiality or publicity rights.";

String privacyPolicyHeaderSixth = "4. AMENDMENTS TO THE POLICY";
String privacyPolicySixth =
    "The ANUBHAV ADHYAYAN Website / App reserves the right to effect revisions/modifications to this Privacy Policy, and any of its other policies or procedures concerning the treatment of information collected through the Website, without prior notice. Any changes to this Privacy Policy will become effective upon posting of the revised Privacy Policy on the Website. Access/use of the Website following the posting of such revised Privacy Policy would be deemed to constitute your acceptance of such revised Privacy Policy, then in effect.";

String privacyPolicyHeaderSeventh = "5. GRIEVANCE OFFICER";
String privacyPolicySeventh =
    "For any queries related to this Privacy Policy, correction of any Personal Information provided by you or for making a complaint about breach of privacy, you may please contact us";

String privacyPolicyHeaderEight = "6. GOVERNING LAW AND DISPUTE RESOLUTION";
String privacyPolicyEight =
    "This Privacy Policy and the Terms and Conditions of Use shall be governed by and construed in accordance with the laws of India. Any and all disputes arising from this Privacy Policy and the Terms and Conditions of Use will be subject to arbitration to be conducted by an independent sole arbitrator (who shall be a retired judge/judicial officer) to be appointed by the ANUBHAV ADHYAYAN Website / App. The arbitration shall be conducted in accordance with the provisions of the Arbitration and Conciliation Act, 1996 (as amended). The arbitration shall be conducted in New Delhi, India and in English language. Subject to arbitration, the jurisdictional courts at New Delhi shall be entitled to grant interim relief/injunction." +
        "\n\nA printed version of this Privacy Policy and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this Privacy Policy to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.";

String privacyPolicyFooter =
    "© 2022 ANUBHAV ADHYAYAN Website / App. All rights reserved.";
